### ISSUE TITLE
Checklist for CRAN release

### ISSUE THREAD

**Issue by gvegayon** [UofUEpiBio/epiworldRShiny#11]
Before sending to CRAN:

- [x] The package CI (GitHub Actions) runs without errors, warnings, or notes in all OS.
- [x] If there are any notes on R CMD check, those are OK (like 'size of the installed package').
- [x] The version is `0.1-0` in the `DESCRIPTION` file.
- [x] The description and title in the `DESCRIPTION` file are sound.
- [x] No extraneous file is included in `R CMD build` (e.g., `.DS_store` or `README.Rmd`).
- [x] The date in the `DESCRIPTION` file is updated.
- [x] Double check grammar in the models' description (markdown files under `inst`).
- [x] Make sure we have included the contributions from the Department of Health and Human Services.

cc @derekmeyer37
